config/routes.rb
Rails.application.routes.draw do
  if ['production', 'staging', 'demo'].include?(Rails.env)
    require 'sidekiq-ent/web'
  else
    require 'sidekiq/web'
  end
   
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  
  require 'sidekiq-status/web'
  authenticate :admin_user, lambda { |u| u.active? && (u.super_user? || u.developer?) } do
    mount Sidekiq::Web, at: 'admin/sidekiq'
  end

  authenticate :admin_user, lambda { |u| u.active? && (u.super_user? || u.support?)  } do
    mount Blazer::Engine, at: "admin/blazer"
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self) rescue ActiveAdmin::DatabaseHitDuringLoad
  get '/linkedin-onboard', to: 'linkedin_login#onboard'
  post '/linkedin-onboard', to: 'linkedin_login#verify_domain'

  get '/admin/loggings', to: 'admin_users/loggings#index';
  get '/admin/integration', to: 'admin_users/loggings#integration';
  get '/admin/webhook_logs', to: 'admin_users/loggings#webhook';
  get '/admin/sapling_api', to: 'admin_users/loggings#sapling_api';
  get '/admin/ct_logs', to: 'admin_users/loggings#ct_logs';
  get '/admin/email_logs', to: 'admin_users/loggings#email_logs';
  get '/admin/pto_logs', to: 'admin_users/loggings#pto_logs';
  get '/admin/overall_logs', to: 'admin_users/loggings#overall_logs';
  get '/admin/papertrail_logs', to: 'admin_users/loggings#papertrail_logs'
  get '/admin/export_loggings', to: 'admin_users/loggings#export_loggings';
  
  get '/admin/general_log/:id', to: 'admin_users/loggings#general_logs_show'
  get '/admin/integration_log/:id', to: 'admin_users/loggings#integration_logs_show'
  get '/admin/api_log/:id', to: 'admin_users/loggings#api_logs_show'
  get '/admin/webhook_log/:id', to: 'admin_users/loggings#webhook_logs_show'
  get '/admin/papertrail_log/:id', to: 'admin_users/loggings#papertrail_logs_show'

  root 'welcome#index'
  get 'check_subdomain', to: 'welcome#check_subdomain'
  match '/orgchart:token' => 'welcome#get_orgchart', :as => 'get_orgchart', via: [:get]
  mount_devise_token_auth_for 'User', at: '/api/v1/auth', controllers: {
    sessions:  'api/v1/auth/sessions',
    passwords:  'api/v1/auth/passwords',
    token_validations: 'api/v1/auth/token_validations',
    registrations: 'api/v1/auth/registrations',
    omniauth_callbacks: 'api/v1/auth/omniauth_callbacks'
  }
  get '/api/health', to: 'welcome#health'
  get '/admin/health', to: 'welcome#health'

  match '/slack_respond' => 'api/v1/admin/slack_integrations#slack_respond', :as => 'slack_respond', via: [:post]
  match '/slack_uninstall' => 'api/v1/admin/slack_integrations#slack_uninstall', :as => 'slack_uninstall', via: [:post]
  match '/slack_auth' => 'api/v1/admin/slack_integrations#slack_auth', :as => 'slack_auth', via: [:get]
  match '/slack_help' => 'api/v1/admin/slack_integrations#slack_help', :as => 'slack_help', via: [:post]
  match '/get_slack_command_data' => 'api/v1/admin/slack_integrations#get_slack_command_data', :as => 'get_team_details', via: [:post]
  match '/api/v1/oauth2callback' => 'api/v1/admin/gsuite_accounts#oauth2callback', :as => 'oauth2callback', via: [:get]
  match '/api/v1/gsheet_oauth2callback' => 'api/v1/admin/gsheets#gsheet_oauth2callback', :as => 'gsheet_oauth2callback', via: [:get]
  match '/smart_recruiters_authorize' => 'api/v1/admin/webhook_integrations/smart_recruiters#smart_recruiters_authorize', :as => 'smart_recruiters_authorize', via: [:get]
  match '/smart_recruiters_authorize/callback' => 'api/v1/admin/webhook_integrations/smart_recruiters#callback', :as => 'smart_recruiters_authorize_callback', via: [:get]
  match '/api/integrations_authorize/callback' => 'api/v1/webhook/integrations_authorize_callback#callback', :as => 'integrations_authorize_callback', via: [:get]
  match '/api/v1/deputy_authorize' => 'api/v1/admin/onboarding_integrations/deputy#authorize', :as => 'authorize', via: [:get]
  match '/api/v1/active_directory_authorize' => 'api/v1/admin/onboarding_integrations/active_directory#active_directory_authorize', :as => 'active_directory_authorize', via: [:get]
  match '/api/v1/beta/profiles/fields/:id' => 'api/v1/beta/profiles#fields', :as => 'fields', via: [:get]
  match '/api/v1/jazz' => 'api/v1/webhook/jazz#create', :as => 'create', via: [:post]
  match '/api/v1/asana' => 'api/v1/webhook/asana#create', :as => 'asana_create', via: [:post]
  match '/api/v1/sendgrid_events' => 'api/v1/webhook/sendgrid#events', :as => 'sendgrid_events', via: [:post]
  match '/api/v1/ats/custom/authenticate' => 'api/v1/webhook/custom_ats#authenticate', :as => 'custom_ats_authenticate', via: [:get]
  match '/api/v1/ats/custom/create' => 'api/v1/webhook/custom_ats#create', :as => 'custom_ats_create', via: [:post]
  match '/gusto-callback' => 'api/v1/admin/onboarding_integrations/gusto#authorize', via: [:get]  
  match '/api/v1/beta/adminsignup' => 'api/v1/beta/signup#create', via: [:post]
  match '/api/v1/beta/userlogin' => 'api/v1/beta/signup#authorize', via: [:get]
  match '/api/v1/beta/passwordstrength' => 'api/v1/beta/signup#password_strength', via: [:get]
  match '/api/v1/beta/profiles/get_sapling_profile' => 'api/v1/beta/profiles#get_sapling_profile', via: [:get]
  match '/api/v1/beta/groupfields/group_fields' => 'api/v1/beta/groupfields#group_fields', :as => 'group_fields', via: [:get]

  get '/403.html' => 'errors#forbidden_error', via: [:get]

  devise_scope :user do
    get '/admin/admin_users/sessions/change_password_form'=>'admin_users/sessions#change_password_form',via: :get
    post '/admin/admin_users/sessions/update_password'=>'admin_users/sessions#update_password',via: :post
  end

  resources :errors, only: [] do
    collection do
      get :not_found
    end
  end
  namespace :api, except: [:new, :edit], defaults: { format: 'json' } do
    namespace :v1 do
      match '/auth/omniauth_callbacks/consume_saml_response' => 'auth/omniauth_callbacks#consume_saml_response', :as => 'consume_saml_response', via: [:post]
      match '/saml/init' => 'saml#init', :as => 'init', via: [:get]
      match '/admin/gsuite_accounts/get_gsuite_auth_credential' => 'admin/gsuite_accounts#get_gsuite_auth_credential', :as => 'get_gsuite_auth_credential', via: [:get]
      match '/admin/gsuite_accounts/remove_credentials' => 'admin/gsuite_accounts#remove_credentials', :as => 'remove_credentials', via: [:get]
      match '/admin/gsheets/get_authorization_status' => 'admin/gsheets#get_authorization_status', :as => 'get_authorization_status', via: [:get]
      match '/admin/gsheets/export_to_google_sheet' => 'admin/gsheets#export_to_google_sheet', :as => 'export_to_google_sheet', via: [:get]
      resources :custom_table_user_snapshots, only: [:create, :destroy, :update, :show] do
        collection do
          post :mass_create
          get :updates_page_ctus
          get :user_approval_snapshot_min_date
          get :paginated_dashboard_approval_requests
          get :email_dashboard_approved_requests
        end
        member do
          get :dashboard_approval_requests
          post :dispatch_request_change_email
        end
      end
      resources :uploaded_files, only: [:create, :update, :destroy] do
        collection do
          post :destroy_all_unused
          post :scan_file
        end
      end
      resources :calendar_events, only: [:index, :show] do
        collection do
          get :get_milestones
        end
      end
      resources :request_informations, only: [:show, :update] do
        collection do
          get :show_request_information_form
        end
      end
      resources :pto_requests do
        collection do
          get :historical_requests
          get :upcoming_requests
          get :get_users_out_of_office
          get :hours_used
        end
        member do
          put :cancel_request
          put :approve_or_deny
        end
      end
      resources :pto_adjustments, only: [:create, :index, :destroy]
      resources :assigned_pto_policies do
        collection do
          get :estimated_balance
        end
      end
      resources :invites, only: [] do
        get '/:token', on: :collection, action: :show, as: :accept_invitation
      end
      resources :companies, only: [] do
        collection do
          get :current
          get :auth_current
        end
      end
      resources :email_activities, only: [:index]
      resources :email_ptos, only: [] do
        member do
          get :approve
          get :deny
          post :post_comment
          get :get_request_by_hash
          get :get_request_user
        end
      end

      resources :manager_forms, only: [:show] do
        collection do
          get :show_manager_form
        end
      end
      resources :workspace_images, only: :index
      resources :company_links, only: :index
      resources :workspaces, only: [:show, :update, :destroy] do
        collection do
          get :basic
        end
      end
      resources :workspace_members, only: [:update, :create, :destroy] do
        collection do
          get :paginated
          get :get_members
        end
      end
      resources :recaptcha, only: [] do
        collection do
          get :verify
        end
      end
      resources :users, only: [:index, :update, :show] do
        resource :profile, only: [:update] do
          member do
            post :create_requested_fields_for_profile_cs_approval
          end
        end
        member do
          get :user_with_pto_policies
          get :basic_info
          post :canny_identify_details
          post :update_ui_switcher
        end
        collection do
          get :email_availibility
          get :paginated
          get :basic
          get :basic_search
          get :home_user
          get :user_with_pending_ptos
          get :people_paginated
          get :total_active_count
          get :dashboard_people_count
          get :get_my_activities_count
          get :get_team_activities_count

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  role_based_authorizable
  extend Devise::Models
  has_paper_trail
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  include AASM

  devise :two_factor_authenticatable, :trackable, :recoverable, :rememberable,
         :otp_secret_encryption_key => ENV['TWO_FACTOR_ENCRYPTION_KEY']

  has_many :active_admin_loggings

  attr_accessor :after_state_change

  after_create :enable_two_factor_authentication
  after_create :send_email_to_admin_user
  after_update :enable_two_factor_authentication, if: Proc.new { |au| au.saved_change_to_state? && au.state == 'active' && !au.after_state_change }
  after_save :update_first_login_as_false, if: Proc.new { |au| au.saved_change_to_sign_in_count? && au.first_login.present? }
  after_save :update_first_login_as_true, if: Proc.new { |au| au.saved_change_to_otp_required_for_login? && au.otp_required_for_login.present? }
  before_create :generate_token_for_authentication

  aasm(:state, column: :state, whiny_transitions: false) do
    state :active, initial: true
    state :inactive

    event :activate do
      transitions from: :inactive, to: :active
    end

    event :deactivate do
      transitions from: :active, to: :inactive
    end
  end

  def setup_two_factor(otp_required_for_login)
    self.otp_required_for_login = otp_required_for_login
    if otp_required_for_login
      self.otp_secret = AdminUser.generate_otp_secret
      self.first_login = true
    end
  end

  def two_fa_status
    self.otp_required_for_login ? 'Enabled' : 'Disabled'
  end

  def enable_two_factor_authentication
    self.otp_required_for_login = true
    self.otp_secret = AdminUser.generate_otp_secret
    self.first_login = true
    self.after_state_change = true
    self.save!
  end

  def update_first_login_as_false
    self.update_column(:first_login, false)
  end

  def update_first_login_as_true
    self.update_column(:first_login, true)
  end

  def send_email_to_admin_user
    UserMailer.admin_user_email(self).deliver_now!
  end

  def generate_token_for_authentication
    encrypted_key = JsonWebToken.encode({email: self.email})
    self.email_verification_token = encrypted_key
  end

end

app/controllers/admin_users/passwords_controller.rb
module AdminUsers
  class PasswordsController < ActiveAdmin::Devise::PasswordsController
    include ::ActiveAdmin::Devise::Controller

    def update
      self.resource = resource_class.reset_password_by_token(resource_params)
      @admin_user = AdminUser.where(email: self.resource.email).first if self.resource.present?         
      if @admin_user.present? && password_equals?
        @admin_user.update_column(:encrypted_password, BCrypt::Password.create(params[:admin_user][:password]))   
        params[:password] = encrypt_password
        if @admin_user.otp_required_for_login                    
          params[:redirect_id] = 0          
          render 'admin_users/sessions/qr_template'
        else
          resource.after_database_authentication
          sign_in(resource_name, resource)
          respond_with resource, location: after_resetting_password_path_for(resource)
        end
      else
        redirect_back(fallback_location: root_path)
      end
    end
    
    protected
    def after_resetting_password_path_for(resource)
      new_session_path(resource_name)
    end

    private
    def password_equals?
      return false unless params[:admin_user][:password] == params[:admin_user][:password_confirmation]
      return true
    end

    def encrypt_password
      crypt = ActiveSupport::MessageEncryptor.new(Rails.application.secrets.secret_key_base)
      password = crypt.encrypt_and_sign(params[:admin_user][:password])
    end    
  end
end

app/controllers/admin_users/sessions_controller.rb
module AdminUsers
  class SessionsController < ActiveAdmin::Devise::SessionsController
    layout 'active_admin_logged_out'
    helper ::ActiveAdmin::ViewHelpers
    before_action :configure_permitted_parameters
    include SetAdminAccessToken
    before_action :check_if_logged_in?, only: [:change_password_form , :update_password]

    def create
      if params[:redirect_id].present? && params[:redirect_id] == "1"
        redirect_to_login_page
        return        
      end
      email = sign_in_params[:email].present? ? sign_in_params[:email] : params[:user_email]
      admin_user = AdminUser.find_for_authentication(email: email) if email.present?
      if admin_user.present?
        if admin_user.active?
          crypt = ActiveSupport::MessageEncryptor.new(Rails.application.secrets.secret_key_base)
          password = sign_in_params[:password].present? ? sign_in_params[:password] : crypt.decrypt_and_verify(params[:password])
          if admin_user.valid_password?(password)
            @admin_user = admin_user
            if admin_user.otp_required_for_login?
              if !sign_in_params[:otp_attempt].present?
                @sign_in_params = sign_in_params
                render :otp_authentication
              else
                set_access_token_on_front_end(@admin_user)
                @admin_user.active_admin_loggings.create!(action: "Admin user #{@admin_user.email} logged in.")
                # warden.set_user(@admin_user, scope: resource_name)
                super
              end
            else
              set_access_token_on_front_end(@admin_user)
              @admin_user.active_admin_loggings.create!(action: "Admin user #{@admin_user.email} logged in.")
              super
            end
          else
            @admin_user = admin_user || AdminUser.new
            flash[:notice] = "Invalid password!"
            redirect_to action: :new
          end
        else
          @admin_user = admin_user || AdminUser.new
          flash[:notice] = "Inactive user. Please activate it to continue!"
          redirect_to action: :new
        end
      else
        @admin_user = admin_user || AdminUser.new
        flash[:notice] = "Invalid email!"
        redirect_to action: :new
      end
    end

    def after_sign_in_path_for(resource)
      admin_dashboard_path
    end

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :password, :otp_attempt])
    end

    def destroy
      current_admin_user.update_column(:access_token, nil)
      cookies.delete :admin_access_token
      super
    end
    
    def change_password_form   
      begin
        user_email = JsonWebToken.decode(params[:token])['email']
        @user = AdminUser.where(:email=>user_email,:email_verification_token=>params[:token]).first
        @user.update_column(:email_verification_token,nil)
      rescue Exception => e
        raise_not_found
      end                
    end

    def update_password
      @admin_user = AdminUser.where(:email=>params[:admin_user][:email]).first      
      if @admin_user.present? && password_equals?                
        @admin_user.update_column(:encrypted_password,BCrypt::Password.create(params[:admin_user][:password]))   
        render 'admin_users/sessions/qr_template'
      else
        redirect_back(fallback_location: root_path)
      end
    end

    def check_if_logged_in?
      raise_not_found if admin_user_signed_in?
    end

    def password_equals?
      return false unless params[:admin_user][:password] == params[:admin_user][:password_confirmation]
      return true
    end

    private

    def redirect_to_login_page
      AdminUser.where(:email=>params[:user_email]).first.update_column(:first_login,FALSE)
      redirect_to action: :new            
    end
  end
end

app/views/admin_users/loggings/_export_loggings_modal.html.erb
<div class="modal fade export_loggings_modal" id="export_loggings_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header export_loggings_header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Your export was successful!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body export_loggings_body">
        <%= "Up to the first 10,000 rows will be exported as a CSV file. The file will be sent to #{current_admin_user.email}. It may take a few minutes to create." %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Done</button>
      </div>
    </div>
  </div>
</div>

app/views/admin_users/loggings/_layout.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Sapling Loggings</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application'  %>
  <%= javascript_include_tag 'application'  %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" >Sapling</a>
      </div>
      <ul class="nav navbar-nav">
        <li><a href="/admin/loggings">Integration</a></li>
        <li><a href="/admin/webhook_logs">Webhook</a></li>
        <li><a href="/admin/sapling_api">Sapling API</a></li>
        <li><a href="/admin/papertrail_logs">Papertrail</a></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">General
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/admin/ct_logs">Custom Table</a></li>
            <li><a href="/admin/pto_logs">PTO</a></li>
            <li><a href="/admin/email_logs">Email</a></li>
            <li><a href="/admin/overall_logs">Overall</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</body>
</html>

app/views/admin_users/loggings/sapling_api.html.erb
  <%= render partial: 'layout' %>
<div class="datatable-margin">
  <div class="row">
    <div class="col-md-10">
      <h2 class="logging-title"> Sapling API Loggings </h2>
      <%= content_tag :table, role: :datatable, class: 'table table-bordered table-hover table-striped dataTable', data: {url: admin_sapling_api_path(format: :json)} do %>
        <thead>
          <tr>
            <th> Company Name </th>
            <th> End Point </th>
            <th> Status</th>
            <th> Created At</th>
            <th>View</th>
          </tr>
        </thead>
        <tbody>
        </tbody>
      <% end %>
    </div>
    <div class="col-md-2 filters">
      <div class="form-group find-by-id">
        <label for="search">Find By ID:</label>
        <input id="api_search" type="text" onkeyup="api_button()" class="form-control">
      </div>
      <input type="hidden"  id="api_hidden" data-toggle="modal" data-target='#api_modal'></button>
      <button type="button" onClick='show_api_logs(0)' id="api_button" class="btn btn-primary" disabled>Search</button>
      <hr/>
      <h1 class="bold">Filters:</h1>
      <form autocomplete="off" onsubmit="return submit_filters()">
        <%= render partial: 'filters' %>
        
        <div class="form-group">
          <label for="status">Status</label>
          <%= select_tag :status, options_for_select(@statuses, params[:status]), class: "form-control"  %>
        </div>

        <div class="form-group">
          <label for="end_point">End Point</label>
          <%= text_field_tag :end_point, params[:end_point], class: "form-control"  %>
        </div>

        <div class="form-group">
          <label for="data_received">Data Received:</label>
          <%= text_field_tag :data_received, params[:data_received], class: "form-control"  %>
        </div>

        <div class="form-group">
          <label for="message">Message</label>
          <%= text_field_tag :message, params[:message], class: "form-control"  %>
        </div>
        <%= render partial: 'date_filters' %>
        <button type="submit" class="btn btn-default">Submit</button>
        <hr>
      </form>
      <%= csrf_meta_tag %>
      <button class="btn btn-default" data-toggle="modal" data-target='#export_loggings_modal' onClick="export_loggings('SaplingApiLogging')">Export Results</button>

    </div>
  </div>
</div>
<div class="modal fade" id="api_modal" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content modals-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Sapling API Log<a href="" id="api_href" style="margin-left: 5px;" target="_blank"> View</a></h4>
      </div>
      <div class="modal-body">

        <form class="madals">
          <div class="form-group">
            <label for="company_name">Company Name:</label>
            <p id="api_company_name" type="text" class="form-control" disabled >
          </div>
          <div class="form-group">
            <label for="company_domain">Company Domain:</label>
            <p id="api_company_domain" type="text" class="form-control" disabled >
          </div>
          <div class="form-group">
            <label for="data_received">Data Received:</label>
            <p id="api_data_received" type="text" class="form-control" disabled >
          </div>
          <div class="form-group">
            <label for="end_point">End Point:</label>
            <p id="api_end_point" type="text" class="form-control" disabled>
          </div>
          <div class="form-group">
            <label for="location">Location:</label>
            <p id="api_location" type="text" class="form-control" disabled>
          </div>
          <div class="form-group">
            <label for="message">Message:</label>
            <p id="api_message" type="text" class="form-control" disabled>
          </div>


          <div class="form-group">
            <label for="status">Status:</label>
            <p id="api_status" type="text" class="form-control" disabled>
          </div>

          <div class="form-group">
            <label for="created_at">Created At:</label>
            <p id="api_created_at" type="text" class="form-control" disabled>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

<%= render partial: 'export_loggings_modal' %>

app/views/admin_users/loggings/webhook.html.erb
<%= render partial: 'layout' %>
<div class="datatable-margin">
  <div class="row">
    <div class="col-md-10">
      <h2 class="logging-title"> Webhook Loggings </h2>
      <%= content_tag :table, role: :datatable, class: 'table table-bordered table-hover table-striped dataTable', data: {url: admin_webhook_logs_path(format: :json)} do %>
        <thead>
          <tr>
            <th> Company Name </th>
            <th> Integration </th>
            <th> Action </th>
            <th> Status </th>
            <th> Created At </th>
            <th> View</th>
          </tr>
        </thead>
        <tbody>
        </tbody>
      <% end %>
    </div>
    <div class="col-md-2 filters">
      
      <div class="form-group find-by-id">
        <label for="search">Find By ID:</label>
        <input id="webhook_search" type="text" onkeyup="webhook_button()" class="form-control">
      </div>
      <input type="hidden"  id="hidden_button" data-toggle="modal" data-target='#webhook_modal'></button>
      <button type="button" onClick='show_webhook_logs(0)' id="webhook_button" class="btn btn-primary" disabled>Search</button>
      <hr/>
      <h1 class="bold">Filters:</h1>
      <form autocomplete="off" onsubmit="return submit_filters()">
        <%= render partial: 'filters' %>

        <div class="form-group">
          <label for="integration">Integration:</label>
          <%= select_tag :integration, options_for_select(@webhook_names, params[:integration]), class: "form-control"  %>
        </div>

        <div class="form-group">
          <label for="status">Status</label>
          <%= select_tag :status, options_for_select(@webhook_statuses, params[:status]), class: "form-control"  %>
        </div>

        <div class="form-group">
          <label for="data_received">Data Received:</label>
          <%= text_field_tag :data_received, params[:data_received], class: "form-control"  %>
        </div>

        <div class="form-group">
          <label for="error_message">Error Message</label>
          <%= text_field_tag :error_message, params[:error_message], class: "form-control"  %>
        </div>

        <div class="form-group">
          <label for="action">Action</label>
          <%= text_field_tag :actions, params[:actions], class: "form-control"  %>
        </div>

        <%= render partial: 'date_filters' %>
        <button type="submit" class="btn btn-default">Submit</button>
        <hr>
      </form>
      <%= csrf_meta_tag %>
      <button class="btn btn-default" data-toggle="modal" data-target='#export_loggings_modal' onClick="export_loggings('WebhookLogging')">Export Results</button>
      
     
    </div>
  </div>
</div>
<div class="modal fade" id="webhook_modal" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content modals-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Webhook Log<a href="" id="webhook_href" style="margin-left: 5px;" target="_blank"> View</a></h4>
      </div>
      <div class="modal-body" id="webhook_modal_body">

        <form class="madals">
          <div class="form-group">
            <label for="company_name">Company Name:</label>
            <p id="webhook_company_name" type="text" class="form-control" disabled >
          </div>
          <div class="form-group">
            <label for="company_domain">Company Domain:</label>
            <p id="webhook_company_domain" type="text" class="form-control" disabled >
          </div>
          <div class="form-group">
            <label for="integration">Integration:</label>
            <p id="webhook_integration" type="text" class="form-control" disabled >
          </div>
          <div class="form-group">
            <label for="data_received">Data Received:</label>
            <p id="webhook_data_received" type="text" class="form-control" disabled >
          </div>
          <div class="form-group">
            <label for="location">Location:</label>
            <p id="webhook_location" type="text" class="form-control" disabled>
          </div>
          <div class="form-group">
            <label for="error_message">Error Message:</label>
            <p id="webhook_error_message" type="text" class="form-control" disabled>
          </div>
          <div class="form-group">
            <label for="action">Action:</label>
            <p id="webhook_action" type="text" class="form-control" disabled>
          </div>

          <div class="form-group">
            <label for="status">Status:</label>
            <p id="webhook_status" type="text" class="form-control" disabled>
          </div>

          <div class="form-group">
            <label for="created_at">Created At:</label>
            <p id="webhook_created_at" type="text" class="form-control" disabled>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

<%= render partial: 'export_loggings_modal' %>